// Code generated by "stringer -type=MessageType -output=stringer_generated.go"; DO NOT EDIT.

use std::fmt;

use crate::protocol_msgpack::MessageType;

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
const _: [(); (MessageType::Unknown).0 as usize] = [(); 0];
const _: [(); (MessageType::Request).0 as usize] = [(); 1];
const _: [(); (MessageType::CallResponse).0 as usize] = [(); 2];
const _: [(); (MessageType::CallError).0 as usize] = [(); 3];
const _: [(); (MessageType::Response).0 as usize] = [(); 4];
const _: [(); (MessageType::Error).0 as usize] = [(); 5];
const _: [(); (MessageType::Call).0 as usize] = [(); 6];

impl MessageType {
    pub fn as_str(self) -> Option<&'static str> {
        match self {
            MessageType::Unknown => Some("MessageTypeUnknown"),
            MessageType::Request => Some("MessageTypeRequest"),
            MessageType::CallResponse => Some("MessageTypeCallResponse"),
            MessageType::CallError => Some("MessageTypeCallError"),
            MessageType::Response => Some("MessageTypeResponse"),
            MessageType::Error => Some("MessageTypeError"),
            MessageType::Call => Some("MessageTypeCall"),
            _ => None,
        }
    }
}

impl fmt::Display for MessageType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(name) => f.write_str(name),
            None => write!(f, "MessageType({})", self.0),
        }
    }
}

// PORT STATUS
//   source:     internal/api/stringer_generated.go (30 lines)
//   confidence: high
//   todos:      0
//   notes:      reviewed against Go; generated discriminant checks, valid strings, and MessageType(n) fallback for unknown numeric values match source behavior.
