use std::fmt;

use crate::LanguageVariant;

// Code generated by "stringer -type=LanguageVariant -output=languagevariant_stringer_generated.go"; DO NOT EDIT.

// An "invalid array length" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
const _: [(); 0] = [(); LanguageVariant::Standard.0 as usize];
const _: [(); 1] = [(); LanguageVariant::JSX.0 as usize];

const _LANGUAGE_VARIANT_NAME: &str = "LanguageVariantStandardLanguageVariantJSX";

const _LANGUAGE_VARIANT_INDEX: [usize; 3] = [0, 23, 41];

impl LanguageVariant {
    pub fn as_str(self) -> Option<&'static str> {
        let idx = self.0;
        if self.0 < 0 || idx as usize >= _LANGUAGE_VARIANT_INDEX.len() - 1 {
            None
        } else {
            let idx = idx as usize;
            Some(
                &_LANGUAGE_VARIANT_NAME
                    [_LANGUAGE_VARIANT_INDEX[idx].._LANGUAGE_VARIANT_INDEX[idx + 1]],
            )
        }
    }
}

impl fmt::Display for LanguageVariant {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(name) => f.write_str(name),
            None => write!(f, "LanguageVariant({})", self.0),
        }
    }
}

// PORT STATUS
//   source:     internal/core/languagevariant_stringer_generated.go (25 lines)
//   confidence: high
//   todos:      0
//   notes:      reviewed against Go; generated String behavior and invalid numeric fallback are ported.
// --------------------------------------------------------------------------
