use std::fmt;

use crate::ModuleKind;

// Code generated by Rust port of "stringer -type=ModuleKind -trimprefix=ModuleKind -output=modulekind_stringer_generated.go"; DO NOT EDIT.

impl ModuleKind {
    pub fn as_str(self) -> Option<&'static str> {
        match self {
            ModuleKind::None => Some("None"),
            ModuleKind::CommonJS => Some("CommonJS"),
            ModuleKind::AMD => Some("AMD"),
            ModuleKind::UMD => Some("UMD"),
            ModuleKind::System => Some("System"),
            ModuleKind::ES2015 => Some("ES2015"),
            ModuleKind::ES2020 => Some("ES2020"),
            ModuleKind::ES2022 => Some("ES2022"),
            ModuleKind::ESNext => Some("ESNext"),
            ModuleKind::Node16 => Some("Node16"),
            ModuleKind::Node18 => Some("Node18"),
            ModuleKind::Node20 => Some("Node20"),
            ModuleKind::NodeNext => Some("NodeNext"),
            ModuleKind::Preserve => Some("Preserve"),
            _ => None,
        }
    }
}

impl fmt::Display for ModuleKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(name) => f.write_str(name),
            None => write!(f, "ModuleKind({})", self.0),
        }
    }
}

// PORT STATUS
//   source:     internal/core/modulekind_stringer_generated.go (52 lines)
//   confidence: high
//   todos:      none
//   notes:      reviewed against Go; generated String behavior and invalid numeric fallback are ported.
