use std::fmt;

use crate::ScriptKind;

// Code generated by Rust port of "stringer -type=ScriptKind -output=scriptkind_stringer_generated.go"; DO NOT EDIT.

impl ScriptKind {
    pub fn as_str(self) -> Option<&'static str> {
        match self {
            ScriptKind::Unknown => Some("ScriptKindUnknown"),
            ScriptKind::JS => Some("ScriptKindJS"),
            ScriptKind::JSX => Some("ScriptKindJSX"),
            ScriptKind::TS => Some("ScriptKindTS"),
            ScriptKind::TSX => Some("ScriptKindTSX"),
            ScriptKind::External => Some("ScriptKindExternal"),
            ScriptKind::JSON => Some("ScriptKindJSON"),
            ScriptKind::Deferred => Some("ScriptKindDeferred"),
            _ => None,
        }
    }
}

impl fmt::Display for ScriptKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(name) => f.write_str(name),
            None => write!(f, "ScriptKind({})", self.0),
        }
    }
}

// PORT STATUS
//   source:     internal/core/scriptkind_stringer_generated.go (31 lines)
//   confidence: high
//   todos:      none
//   notes:      reviewed against Go; generated String behavior and invalid numeric fallback are ported.
