use std::fmt;

use crate::ScriptTarget;

// Code generated by Rust port of "stringer -type=ScriptTarget -trimprefix=ScriptTarget -output=scripttarget_stringer_generated.go"; DO NOT EDIT.

impl ScriptTarget {
    pub fn as_str(self) -> Option<&'static str> {
        match self {
            ScriptTarget::None => Some("None"),
            ScriptTarget::ES5 => Some("ES5"),
            ScriptTarget::ES2015 => Some("ES2015"),
            ScriptTarget::ES2016 => Some("ES2016"),
            ScriptTarget::ES2017 => Some("ES2017"),
            ScriptTarget::ES2018 => Some("ES2018"),
            ScriptTarget::ES2019 => Some("ES2019"),
            ScriptTarget::ES2020 => Some("ES2020"),
            ScriptTarget::ES2021 => Some("ES2021"),
            ScriptTarget::ES2022 => Some("ES2022"),
            ScriptTarget::ES2023 => Some("ES2023"),
            ScriptTarget::ES2024 => Some("ES2024"),
            ScriptTarget::ES2025 => Some("ES2025"),
            ScriptTarget::ESNext => Some("ESNext"),
            ScriptTarget::JSON => Some("JSON"),
            _ => None,
        }
    }
}

impl fmt::Display for ScriptTarget {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(name) => f.write_str(name),
            None => write!(f, "ScriptTarget({})", self.0),
        }
    }
}

// PORT STATUS
//   source:     internal/core/scripttarget_stringer_generated.go (50 lines)
//   confidence: high
//   todos:      none
//   notes:      reviewed against Go; generated String behavior, alias values, and invalid numeric fallback are ported.
