use std::fmt;

use crate::Tristate;

// Code generated by Rust port of "stringer -type=Tristate -output=tristate_stringer_generated.go"; DO NOT EDIT.

impl Tristate {
    pub fn as_str(self) -> Option<&'static str> {
        match self {
            Tristate::Unknown => Some("TSUnknown"),
            Tristate::False => Some("TSFalse"),
            Tristate::True => Some("TSTrue"),
            _ => None,
        }
    }
}

impl fmt::Display for Tristate {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(name) => f.write_str(name),
            None => write!(f, "Tristate({})", self.0),
        }
    }
}

// PORT STATUS
//   source:     internal/core/tristate_stringer_generated.go (26 lines)
//   confidence: high
//   todos:      none
//   notes:      reviewed against Go; generated String behavior and invalid numeric fallback are ported.
