#![allow(dead_code)]

use std::collections::{HashMap, HashSet};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use flate2::Compression;
use flate2::write::GzEncoder;
use regex::Regex;
use serde::Deserialize;
use ts_collections::OrderedMap;
use ts_json as json;
use ts_repo as repo;

#[derive(Deserialize)]
struct DiagnosticMessage {
    #[serde(rename = "category")]
    category: String,
    #[serde(rename = "code")]
    code: i32,
    #[serde(rename = "reportsUnnecessary", default)]
    reports_unnecessary: bool,
    #[serde(rename = "reportsDeprecated", default)]
    reports_deprecated: bool,
    // spelling error here is [sic] in Strada
    #[serde(rename = "elidedInCompatabilityPyramid", default)]
    elided_in_compatibility_pyramid: bool,

    #[serde(default)]
    key: String,
}

#[derive(Deserialize)]
struct Lcx {
    #[serde(rename = "@TgtCul")]
    tgt_cul: String,
    #[serde(rename = "Item", default)]
    root_items: Vec<RootItem>,
}

#[derive(Deserialize)]
struct RootItem {
    #[serde(rename = "@ItemId")]
    item_id: String,
    #[serde(rename = "Item", default)]
    items: Vec<StringTableItem>,
}

#[derive(Deserialize)]
struct StringTableItem {
    #[serde(rename = "@ItemId")]
    item_id: String,
    #[serde(rename = "Item", default)]
    items: Vec<LocalizedItem>,
}

#[derive(Deserialize)]
struct LocalizedItem {
    #[serde(rename = "@ItemId")]
    item_id: String,
    #[serde(rename = "Str")]
    str_: Str,
}

#[derive(Deserialize)]
struct Str {
    #[serde(rename = "Val")]
    val: String,
    #[serde(rename = "Tgt")]
    tgt: Option<Tgt>,
}

#[derive(Deserialize)]
struct Tgt {
    #[serde(rename = "Val")]
    val: String,
}

struct LocaleInfo {
    var_name: String,
    tgt_cul: String,
    canonical: String,
    lang: String,
    filename: String,
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let diagnostics_output = flag_value(&args, "-diagnostics");
    let loc_output = flag_value(&args, "-loc");
    let loc_dir = flag_value(&args, "-locdir");

    if diagnostics_output.is_empty() || loc_output.is_empty() || loc_dir.is_empty() {
        eprintln!("usage: generate -diagnostics <file> -loc <file> -locdir <dir>");
        return;
    }

    let mut raw_diagnostic_messages = read_raw_messages(
        &repo::type_script_submodule_path().join("src/compiler/diagnosticMessages.json"),
    );

    let source_dir = Path::new(file!())
        .parent()
        .unwrap_or_else(|| Path::new("."));
    let local_extra_messages = source_dir.join("extraDiagnosticMessages.json");
    let extra_messages = if local_extra_messages.is_file() {
        local_extra_messages
    } else {
        repo::root_path()
            .join("internal")
            .join("diagnostics")
            .join("extraDiagnosticMessages.json")
    };
    let raw_extra_messages = read_raw_messages(&extra_messages);

    raw_diagnostic_messages.extend(raw_extra_messages);
    let mut diagnostic_messages: Vec<_> = raw_diagnostic_messages.into_values().collect();

    diagnostic_messages.sort_by_key(|a| a.code);

    // Collect known keys for filtering localizations
    let mut known_keys = HashMap::with_capacity(diagnostic_messages.len());
    for m in &diagnostic_messages {
        let (_, key) = convert_property_name(&m.key, m.code);
        known_keys.insert(key, true);
    }

    // Generate diagnostics file
    let diagnostics_buf = generate_diagnostics(&diagnostic_messages);

    if let Err(err) = fs::write(&diagnostics_output, diagnostics_buf) {
        panic!("failed to write diagnostics output: {err}");
    }

    // Generate localizations file
    let loc_buf = generate_localizations(&known_keys, &loc_dir);

    if let Err(err) = fs::write(&loc_output, loc_buf) {
        panic!("failed to write localizations output: {err}");
    }
}

fn flag_value(args: &[String], name: &str) -> String {
    args.windows(2)
        .find(|pair| pair[0] == name)
        .map(|pair| pair[1].clone())
        .unwrap_or_default()
}

fn generate_diagnostics(diagnostic_messages: &[DiagnosticMessage]) -> Vec<u8> {
    let mut buf = String::new();

    buf.push_str("// Code generated by generate.go; DO NOT EDIT.\n");
    buf.push('\n');
    buf.push_str("#![allow(non_upper_case_globals)]\n");
    buf.push('\n');
    buf.push_str("use std::sync::LazyLock;\n");
    buf.push('\n');
    buf.push_str("use crate::{Category, Key, Message};\n");
    buf.push('\n');

    for m in diagnostic_messages {
        let (var_name, key) = convert_property_name(&m.key, m.code);

        buf.push_str(&format!(
            "pub static {var_name}: LazyLock<Message> = LazyLock::new(|| Message {{\n    \
             code: {},\n    \
             category: Category::{},\n    \
             key: {:?}.to_owned(),\n    \
             text: {:?}.to_owned(),\n    \
             reports_unnecessary: {},\n    \
             elided_in_compatibility_pyramid: {},\n    \
             reports_deprecated: {},\n\
             }});\n\n",
            m.code,
            m.category,
            key,
            m.key,
            m.reports_unnecessary,
            m.elided_in_compatibility_pyramid,
            m.reports_deprecated
        ));
    }

    buf.push_str("pub fn key_to_message_generated(key: &Key) -> Option<&'static Message> {\n");
    buf.push_str("    match key.as_str() {\n");
    for m in diagnostic_messages {
        let (_, key) = convert_property_name(&m.key, m.code);
        let (var_name, _) = convert_property_name(&m.key, m.code);
        buf.push_str(&format!("        {key:?} => Some(&{var_name}),\n"));
    }
    buf.push_str("        _ => None,\n");
    buf.push_str("    }\n");
    buf.push_str("}\n");
    buf.push('\n');
    buf.push_str("// --------------------------------------------------------------------------\n");
    buf.push_str("// PORT STATUS\n");
    buf.push_str("//   source:     internal/diagnostics/diagnostics_generated.go (8622 lines)\n");
    buf.push_str("//   confidence: high\n");
    buf.push_str("//   todos:      none\n");
    buf.push_str("//   notes:      generated diagnostic message catalog translated to LazyLock\n");
    buf.push_str("//               statics plus key lookup in Go source order\n");
    buf.push_str("// --------------------------------------------------------------------------\n");

    buf.into_bytes()
}

fn generate_localizations(known_keys: &HashMap<String, bool>, loc_dir: &str) -> Vec<u8> {
    let mut buf = String::new();

    buf.push_str("// Code generated by generate.go; DO NOT EDIT.\n");
    buf.push('\n');
    buf.push_str("#![allow(non_snake_case, non_upper_case_globals)]\n");
    buf.push('\n');
    buf.push_str("use std::collections::HashMap;\n");
    buf.push_str("use std::sync::LazyLock;\n");
    buf.push('\n');
    buf.push_str("use flate2::read::GzDecoder;\n");
    buf.push_str("use ts_json as json;\n");
    buf.push_str("use ts_locale as locale;\n");
    buf.push('\n');
    buf.push_str("use crate::Key;\n");
    buf.push('\n');

    // Remove and recreate the loc directory for a clean state
    if let Err(err) = fs::remove_dir_all(loc_dir)
        && Path::new(loc_dir).exists()
    {
        panic!("failed to remove locale directory: {err}");
    }
    if let Err(err) = fs::create_dir_all(loc_dir) {
        panic!("failed to create locale directory: {err}");
    }

    // Generate locale maps
    let locale_glob = repo::type_script_submodule_path().join("src/loc/lcl");
    let mut locale_files = Vec::new();
    collect_locale_files(&locale_glob, &mut locale_files);
    locale_files.sort();

    let mut locales = Vec::new();

    if locale_files.is_empty() {
        collect_prebuilt_locale_infos(&mut locales);
    }

    for locale_file in locale_files {
        let (mut localized_messages, tgt_cul) = read_localized_messages(&locale_file);
        if localized_messages.is_empty() {
            continue;
        }

        // Filter to only known keys
        localized_messages.retain(|key, _| known_keys.contains_key(key));

        if localized_messages.is_empty() {
            continue;
        }

        // Convert locale code to valid Go identifier
        let locale_var = tgt_cul.replace(['-', '_'], "");

        let lang = tgt_cul.split('-').next().unwrap_or("").to_lowercase();

        // Get canonical form (lowercase with dash)
        let canonical = tgt_cul.to_lowercase();

        // Filename for the JSON.gz file (use the original tgtCul as standard language tag)
        let filename = format!("{tgt_cul}.json.gz");

        // Write the JSON.gz file
        // Convert map to OrderedMap with sorted keys for consistent ordering
        let mut keys: Vec<_> = localized_messages.keys().cloned().collect();
        keys.sort();
        let mut ordered_messages = OrderedMap::new();
        for key in keys {
            ordered_messages.set(key.clone(), localized_messages[&key].clone());
        }
        let json_data = json::marshal(&ordered_messages, &[]).unwrap_or_else(|err| {
            panic!("failed to marshal locale {tgt_cul}: {err}");
        });

        let mut gzip_writer = GzEncoder::new(Vec::new(), Compression::best());
        gzip_writer
            .write_all(&json_data)
            .unwrap_or_else(|err| panic!("failed to compress locale {tgt_cul}: {err}"));
        let compressed = gzip_writer.finish().unwrap_or_else(|err| {
            panic!("failed to close gzip writer for locale {tgt_cul}: {err}")
        });

        let output_path = Path::new(loc_dir).join(&filename);
        if let Err(err) = fs::write(&output_path, compressed) {
            panic!(
                "failed to write locale file {}: {err}",
                output_path.display()
            );
        }

        locales.push(LocaleInfo {
            var_name: locale_var,
            tgt_cul,
            canonical,
            lang,
            filename,
        });
    }

    buf.push_str("fn normalize_locale_tag(tag: &str) -> String {\n");
    buf.push_str("\ttag.split('.')\n");
    buf.push_str("\t\t.next()\n");
    buf.push_str("\t\t.unwrap_or(tag)\n");
    buf.push_str("\t\t.to_ascii_lowercase()\n");
    buf.push_str("\t\t.replace('_', \"-\")\n");
    buf.push_str("}\n\n");
    buf.push_str("fn locale_parts(tag: &str) -> Vec<&str> {\n");
    buf.push_str("\ttag.split('-')\n");
    buf.push_str("\t\t.filter(|part| !part.is_empty())\n");
    buf.push_str("\t\t.take_while(|part| *part != \"x\" && part.len() != 1)\n");
    buf.push_str("\t\t.collect()\n");
    buf.push_str("}\n\n");
    buf.push_str("fn matcher_index(tag: &str) -> usize {\n");
    buf.push_str("\tlet normalized = normalize_locale_tag(tag);\n");
    buf.push_str("\tmatch normalized.as_str() {\n");
    buf.push_str("\t\t\"en\" => 0,\n");
    for loc in &locales {
        buf.push_str(&format!(
            "\t\t{:?} => {},\n",
            loc.canonical,
            locales
                .iter()
                .position(|candidate| candidate.canonical == loc.canonical)
                .unwrap()
                + 1
        ));
    }
    buf.push_str("\t\t_ => match locale_parts(&normalized).as_slice() {\n");
    let mut emitted_langs = HashSet::new();
    for loc in &locales {
        if emitted_langs.insert(loc.lang.clone()) {
            if loc.lang == "zh" {
                let simplified_index = locales
                    .iter()
                    .position(|candidate| candidate.canonical == "zh-cn")
                    .unwrap()
                    + 1;
                let traditional_index = locales
                    .iter()
                    .position(|candidate| candidate.canonical == "zh-tw")
                    .unwrap()
                    + 1;
                buf.push_str("\t\t\t[\"zh\", rest @ ..] => {\n");
                buf.push_str("\t\t\t\tlet has_hant = rest.iter().any(|part| *part == \"hant\");\n");
                buf.push_str("\t\t\t\tlet has_hans = rest.iter().any(|part| *part == \"hans\");\n");
                buf.push_str("\t\t\t\tlet has_traditional_region = rest\n");
                buf.push_str("\t\t\t\t\t.iter()\n");
                buf.push_str("\t\t\t\t\t.any(|part| matches!(*part, \"tw\" | \"hk\" | \"mo\"));\n");
                buf.push_str("\t\t\t\tif has_hant || (!has_hans && has_traditional_region) {\n");
                buf.push_str(&format!("\t\t\t\t\t{traditional_index}\n"));
                buf.push_str("\t\t\t\t} else {\n");
                buf.push_str(&format!("\t\t\t\t\t{simplified_index}\n"));
                buf.push_str("\t\t\t\t}\n");
                buf.push_str("\t\t\t},\n");
            } else {
                buf.push_str(&format!(
                    "\t\t\t[{:?}, ..] => {},\n",
                    loc.lang,
                    locales
                        .iter()
                        .position(|candidate| candidate.canonical == loc.canonical)
                        .unwrap()
                        + 1
                ));
            }
        }
    }
    buf.push_str("\t\t\t_ => 0,\n");
    buf.push_str("\t\t},\n");
    buf.push_str("\t}\n");
    buf.push_str("}\n\n");
    buf.push_str("pub fn matcher_match_generated(loc: locale::Locale) -> Option<usize> {\n");
    buf.push_str("\tif loc.is_und() {\n");
    buf.push_str("\t\treturn None;\n");
    buf.push_str("\t}\n");
    buf.push_str("\tSome(matcher_index(loc.as_str()))\n");
    buf.push_str("}\n\n");

    buf.push_str("type LocaleFunc = fn() -> HashMap<Key, String>;\n\n");
    buf.push_str("pub fn locale_funcs_generated() -> Vec<Option<LocaleFunc>> {\n");
    buf.push_str("\tvec![\n");
    buf.push_str("\t\tNone,\n");
    for loc in &locales {
        buf.push_str(&format!("\t\tSome({}),\n", loc.var_name));
    }
    buf.push_str("\t]\n");
    buf.push_str("}\n\n");

    buf.push_str("fn load_locale_data(data: &[u8]) -> HashMap<Key, String> {\n");
    buf.push_str("\tlet mut gr = GzDecoder::new(data);\n");
    buf.push_str("\tlet mut result = HashMap::new();\n");
    buf.push_str("\tjson::unmarshal_read(&mut gr, &mut result, &[])\n");
    buf.push_str(
        "\t\t.unwrap_or_else(|err| panic!(\"failed to unmarshal locale data: {err}\"));\n",
    );
    buf.push_str("\tresult\n");
    buf.push_str("}\n");

    // Generate embed directives, vars, and loader functions interleaved at the bottom
    for loc in &locales {
        let cache_name = format!("{}_CACHE", loc.var_name.to_ascii_uppercase());
        buf.push_str(&format!(
            "\nstatic {}Data: &[u8] = include_bytes!(concat!(\"../../../vendor/typescript-go/internal/diagnostics/loc/\", {:?}));\n",
            loc.var_name, loc.filename
        ));
        buf.push_str(&format!(
            "\nstatic {cache_name}: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data({}Data));\n",
            loc.var_name
        ));
        buf.push_str(&format!(
            "\nfn {}() -> HashMap<Key, String> {{\n\t{cache_name}.clone()\n}}\n",
            loc.var_name
        ));
    }

    buf.into_bytes()
}

fn collect_prebuilt_locale_infos(locales: &mut Vec<LocaleInfo>) {
    let loc_dir = repo::root_path()
        .join("internal")
        .join("diagnostics")
        .join("loc");
    let Ok(entries) = fs::read_dir(&loc_dir) else {
        panic!("no locale files found in {}", loc_dir.display());
    };

    let mut files = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        let Some(filename) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if filename.ends_with(".json.gz") {
            files.push(filename.to_owned());
        }
    }

    if files.is_empty() {
        panic!("no locale files found in {}", loc_dir.display());
    }

    let preferred_order = [
        "zh-CN.json.gz",
        "zh-TW.json.gz",
        "cs-CZ.json.gz",
        "de-DE.json.gz",
        "es-ES.json.gz",
        "fr-FR.json.gz",
        "it-IT.json.gz",
        "ja-JP.json.gz",
        "ko-KR.json.gz",
        "pl-PL.json.gz",
        "pt-BR.json.gz",
        "ru-RU.json.gz",
        "tr-TR.json.gz",
    ];
    files.sort_by_key(|filename| {
        preferred_order
            .iter()
            .position(|candidate| candidate == filename)
            .unwrap_or(preferred_order.len())
    });
    for filename in files {
        let tgt_cul = filename.trim_end_matches(".json.gz").to_owned();
        locales.push(LocaleInfo {
            var_name: tgt_cul.replace(['-', '_'], ""),
            lang: tgt_cul.split('-').next().unwrap_or("").to_lowercase(),
            canonical: tgt_cul.to_lowercase(),
            tgt_cul,
            filename,
        });
    }
}

fn collect_locale_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let locale_dir = entry.path();
        if locale_dir.is_dir() {
            let path = locale_dir
                .join("diagnosticMessages")
                .join("diagnosticMessages.generated.json.lcl");
            if path.is_file() {
                out.push(path);
            }
        }
    }
}

fn read_raw_messages(p: &Path) -> HashMap<i32, DiagnosticMessage> {
    let file = fs::read_to_string(p).unwrap_or_else(|err| panic!("failed to open file: {err}"));

    let mut raw_messages: HashMap<String, DiagnosticMessage> =
        serde_json::from_str(&file).unwrap_or_else(|err| panic!("failed to decode file: {err}"));

    let mut code_to_message = HashMap::with_capacity(raw_messages.len());
    for (k, mut m) in raw_messages.drain() {
        m.key = k;
        code_to_message.insert(m.code, m);
    }

    code_to_message
}

fn read_localized_messages(p: &Path) -> (HashMap<String, String>, String) {
    let file = fs::read_to_string(p).unwrap_or_else(|err| {
        eprintln!("failed to open locale file {}: {err}", p.display());
        String::new()
    });
    if file.is_empty() {
        return (HashMap::new(), String::new());
    }

    let lcx: Lcx = quick_xml::de::from_str(&file).unwrap_or_else(|err| {
        eprintln!("failed to decode locale file {}: {err}", p.display());
        Lcx {
            tgt_cul: String::new(),
            root_items: Vec::new(),
        }
    });

    let mut messages = HashMap::new();

    // Navigate the nested Item structure
    for root_item in &lcx.root_items {
        for string_table in &root_item.items {
            for item in &string_table.items {
                // ItemId has format ";key_code", remove the leading semicolon
                let item_id = item
                    .item_id
                    .strip_prefix(';')
                    .unwrap_or(&item.item_id)
                    .to_string();

                // Get the localized text from Tgt if available, otherwise use Val
                let text = if item
                    .str_
                    .tgt
                    .as_ref()
                    .is_some_and(|tgt| !tgt.val.is_empty())
                {
                    item.str_.tgt.as_ref().unwrap().val.clone()
                } else {
                    item.str_.val.clone()
                };

                messages.insert(item_id, text);
            }
        }
    }

    (messages, lcx.tgt_cul)
}

fn multiple_underscore_regexp() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"_+").unwrap())
}

fn leading_underscore_unless_digit_regexp() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^_+(\D)").unwrap())
}

fn trailing_underscore_regexp() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"_$").unwrap())
}

fn convert_property_name(orig_name: &str, code: i32) -> (String, String) {
    let mut b = String::with_capacity(orig_name.len());

    for r in orig_name.chars() {
        match r {
            '*' => b.push_str("_Asterisk"),
            '/' => b.push_str("_Slash"),
            ':' => b.push_str("_Colon"),
            _ => {
                if !r.is_alphabetic() && !r.is_ascii_digit() {
                    b.push('_');
                } else {
                    b.push(r);
                }
            }
        }
    }

    let mut var_name = b;
    // get rid of all multi-underscores
    var_name = multiple_underscore_regexp()
        .replace_all(&var_name, "_")
        .to_string();
    // remove any leading underscore, unless it is followed by a number.
    var_name = leading_underscore_unless_digit_regexp()
        .replace_all(&var_name, "$1")
        .to_string();
    // get rid of all trailing underscores.
    var_name = trailing_underscore_regexp()
        .replace_all(&var_name, "")
        .to_string();

    let mut key = var_name.clone();
    if key.len() > 100 {
        key.truncate(100);
    }
    key = format!("{key}_{code}");

    if !is_exported(&var_name) {
        let mut b = String::with_capacity(var_name.len() + 2);
        if var_name.starts_with('_') {
            b.push('X');
        } else {
            b.push_str("X_");
        }
        b.push_str(&var_name);
        var_name = b;
    }

    if !is_identifier(&var_name) || !is_exported(&var_name) {
        panic!("failed to convert property name to exported identifier: {orig_name:?}");
    }

    (var_name, key)
}

fn is_exported(name: &str) -> bool {
    name.chars().next().is_some_and(|ch| ch.is_uppercase())
}

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first.is_alphabetic()) && chars.all(|ch| ch == '_' || ch.is_alphanumeric())
}
