// Code generated by generate.go; DO NOT EDIT.

#![allow(non_snake_case, non_upper_case_globals)]

use std::collections::HashMap;
use std::sync::LazyLock;

use flate2::read::GzDecoder;
use ts_json as json;
use ts_locale as locale;

use crate::Key;

fn normalize_locale_tag(tag: &str) -> String {
    tag.split('.')
        .next()
        .unwrap_or(tag)
        .to_ascii_lowercase()
        .replace('_', "-")
}

fn locale_parts(tag: &str) -> Vec<&str> {
    tag.split('-')
        .filter(|part| !part.is_empty())
        .take_while(|part| *part != "x" && part.len() != 1)
        .collect()
}

fn matcher_index(tag: &str) -> usize {
    let normalized = normalize_locale_tag(tag);
    match normalized.as_str() {
        "en" => 0,
        "zh-cn" => 1,
        "zh-tw" => 2,
        "cs-cz" => 3,
        "de-de" => 4,
        "es-es" => 5,
        "fr-fr" => 6,
        "it-it" => 7,
        "ja-jp" => 8,
        "ko-kr" => 9,
        "pl-pl" => 10,
        "pt-br" => 11,
        "ru-ru" => 12,
        "tr-tr" => 13,
        _ => match locale_parts(&normalized).as_slice() {
            ["zh", rest @ ..] => {
                if rest
                    .iter()
                    .any(|part| matches!(*part, "hant" | "tw" | "hk" | "mo"))
                {
                    2
                } else {
                    1
                }
            }
            ["cs", ..] => 3,
            ["de", ..] => 4,
            ["es", ..] => 5,
            ["fr", ..] => 6,
            ["it", ..] => 7,
            ["ja", ..] => 8,
            ["ko", ..] => 9,
            ["pl", ..] => 10,
            ["pt", ..] => 11,
            ["ru", ..] => 12,
            ["tr", ..] => 13,
            _ => 0,
        },
    }
}

pub fn matcher_match_generated(loc: locale::Locale) -> Option<usize> {
    if loc.is_und() {
        return None;
    }
    Some(matcher_index(loc.as_str()))
}

type LocaleFunc = fn() -> HashMap<Key, String>;

pub fn locale_funcs_generated() -> Vec<Option<LocaleFunc>> {
    vec![
        None,
        Some(zhCN),
        Some(zhTW),
        Some(csCZ),
        Some(deDE),
        Some(esES),
        Some(frFR),
        Some(itIT),
        Some(jaJP),
        Some(koKR),
        Some(plPL),
        Some(ptBR),
        Some(ruRU),
        Some(trTR),
    ]
}

fn load_locale_data(data: &[u8]) -> HashMap<Key, String> {
    let mut gr = GzDecoder::new(data);
    let mut result = HashMap::new();
    json::unmarshal_read(&mut gr, &mut result, &[])
        .unwrap_or_else(|err| panic!("failed to unmarshal locale data: {err}"));
    result
}

static zhCNData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "zh-CN.json.gz"
));

static ZHCN_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(zhCNData));

fn zhCN() -> HashMap<Key, String> {
    ZHCN_CACHE.clone()
}

static zhTWData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "zh-TW.json.gz"
));

static ZHTW_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(zhTWData));

fn zhTW() -> HashMap<Key, String> {
    ZHTW_CACHE.clone()
}

static csCZData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "cs-CZ.json.gz"
));

static CSCZ_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(csCZData));

fn csCZ() -> HashMap<Key, String> {
    CSCZ_CACHE.clone()
}

static deDEData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "de-DE.json.gz"
));

static DEDE_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(deDEData));

fn deDE() -> HashMap<Key, String> {
    DEDE_CACHE.clone()
}

static esESData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "es-ES.json.gz"
));

static ESES_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(esESData));

fn esES() -> HashMap<Key, String> {
    ESES_CACHE.clone()
}

static frFRData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "fr-FR.json.gz"
));

static FRFR_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(frFRData));

fn frFR() -> HashMap<Key, String> {
    FRFR_CACHE.clone()
}

static itITData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "it-IT.json.gz"
));

static ITIT_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(itITData));

fn itIT() -> HashMap<Key, String> {
    ITIT_CACHE.clone()
}

static jaJPData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "ja-JP.json.gz"
));

static JAJP_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(jaJPData));

fn jaJP() -> HashMap<Key, String> {
    JAJP_CACHE.clone()
}

static koKRData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "ko-KR.json.gz"
));

static KOKR_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(koKRData));

fn koKR() -> HashMap<Key, String> {
    KOKR_CACHE.clone()
}

static plPLData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "pl-PL.json.gz"
));

static PLPL_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(plPLData));

fn plPL() -> HashMap<Key, String> {
    PLPL_CACHE.clone()
}

static ptBRData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "pt-BR.json.gz"
));

static PTBR_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(ptBRData));

fn ptBR() -> HashMap<Key, String> {
    PTBR_CACHE.clone()
}

static ruRUData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "ru-RU.json.gz"
));

static RURU_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(ruRUData));

fn ruRU() -> HashMap<Key, String> {
    RURU_CACHE.clone()
}

static trTRData: &[u8] = include_bytes!(concat!(
    "../../../vendor/typescript-go/internal/diagnostics/loc/",
    "tr-TR.json.gz"
));

static TRTR_CACHE: LazyLock<HashMap<Key, String>> = LazyLock::new(|| load_locale_data(trTRData));

fn trTR() -> HashMap<Key, String> {
    TRTR_CACHE.clone()
}

// --------------------------------------------------------------------------
// PORT STATUS
//   source:     internal/diagnostics/loc_generated.go (151 lines)
//   confidence: high
//   todos:      none
//   notes:      reviewed against Go; locale order, embedded asset mapping, exact matches,
//               base-language fallback, and Simplified/Traditional Chinese script/region fallback are preserved.
// --------------------------------------------------------------------------
