// Code generated by "stringer -type=Category -output=stringer_generated.go"; DO NOT EDIT.

use std::fmt;

use crate::Category;

impl Category {
    pub fn as_str(self) -> Option<&'static str> {
        match self {
            Category::Warning => Some("CategoryWarning"),
            Category::Error => Some("CategoryError"),
            Category::Suggestion => Some("CategorySuggestion"),
            Category::Message => Some("CategoryMessage"),
            _ => None,
        }
    }
}

impl fmt::Display for Category {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_str() {
            Some(name) => f.write_str(name),
            None => write!(f, "Category({})", self.0),
        }
    }
}

// PORT STATUS
//   source:     internal/diagnostics/stringer_generated.go (27 lines)
//   confidence: high
//   todos:      none
//   notes:      reviewed against Go; generated String behavior and invalid numeric fallback are ported.
