use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let generated_path = out_dir.join("compiler_baselines_generated.rs");
    let mut generated = String::new();
    generated.push_str("// @generated by crates/ts-testrunner/build.rs\n\n");

    let typescript_root = type_script_submodule_path();
    let cases = typescript_root.join("tests").join("cases");
    let compiler = cases.join("compiler");
    let conformance = cases.join("conformance");
    assert!(
        compiler.is_dir() && conformance.is_dir(),
        "expected TypeScript tests at {}",
        cases.display()
    );
    println!("cargo:rerun-if-changed={}", compiler.display());
    println!("cargo:rerun-if-changed={}", conformance.display());
    println!(
        "cargo:rerun-if-changed={}",
        compiler_test_skip_path().display()
    );

    write_suite_tests(
        &mut generated,
        "compiler",
        "CompilerTestType::Regression",
        &compiler,
    )
    .expect("failed to generate compiler baseline tests");
    write_suite_tests(
        &mut generated,
        "conformance",
        "CompilerTestType::Conformance",
        &conformance,
    )
    .expect("failed to generate conformance baseline tests");

    fs::write(generated_path, generated).expect("failed to write generated baseline tests");
}

fn type_script_submodule_path() -> PathBuf {
    workspace_root()
        .join("vendor")
        .join("typescript-go")
        .join("_submodules")
        .join("TypeScript")
}

fn workspace_root() -> PathBuf {
    let manifest_dir = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap());
    manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("ts_testrunner is under crates/")
        .to_owned()
}

fn compiler_test_skip_path() -> PathBuf {
    PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap())
        .join("compiler_test_skip_files.txt")
}

fn skipped_tests() -> HashSet<&'static str> {
    include_str!("compiler_test_skip_files.txt")
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .collect()
}

fn should_skip_test_file(filename: &str) -> bool {
    let basename = Path::new(filename)
        .file_name()
        .and_then(|filename| filename.to_str())
        .unwrap_or(filename);
    if skipped_tests().contains(basename) {
        return true;
    }

    let filename = filename.replace('\\', "/").to_ascii_lowercase();
    let basename = basename.to_ascii_lowercase();
    filename.contains("jsdoc") || basename.contains("typedef")
}

fn contains_jsdoc_test_content(content: &str) -> bool {
    const JSDOC_TAGS: [&str; 23] = [
        "@augments",
        "@callback",
        "@class",
        "@constructor",
        "@enum",
        "@extends",
        "@implements",
        "@import",
        "@member",
        "@memberof",
        "@module",
        "@overload",
        "@override",
        "@param",
        "@property",
        "@returns",
        "@return",
        "@satisfies",
        "@template",
        "@this",
        "@typedef",
        "@type",
        "@yield",
    ];
    content.contains("/**") && JSDOC_TAGS.iter().any(|tag| content.contains(tag))
}

fn write_suite_tests(
    generated: &mut String,
    suite_name: &str,
    test_type: &str,
    suite_path: &Path,
) -> io::Result<()> {
    let mut files = Vec::new();
    if suite_path.is_dir() {
        enumerate_test_files(suite_path, suite_path, &mut files)?;
    }
    files.sort();

    for relative_path in files {
        let bytes = fs::read(suite_path.join(&relative_path))?;
        let content = decode_bytes(&bytes).ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!("{relative_path} could not be decoded"),
            )
        })?;
        if should_skip_test_file(&relative_path) || contains_jsdoc_test_content(&content) {
            continue;
        }
        let configurations = file_based_test_configurations(&extract_compiler_settings(&content));
        if configurations.is_empty() {
            write_config_test(generated, suite_name, test_type, &relative_path, None, "")?;
        } else {
            for (index, config_name) in configurations.iter().enumerate() {
                write_config_test(
                    generated,
                    suite_name,
                    test_type,
                    &relative_path,
                    Some(index),
                    config_name,
                )?;
            }
        }
    }

    Ok(())
}

fn write_config_test(
    generated: &mut String,
    suite_name: &str,
    test_type: &str,
    relative_path: &str,
    config_index: Option<usize>,
    config_name: &str,
) -> io::Result<()> {
    let test_name = test_name(suite_name, relative_path, config_name);
    writeln!(generated, "#[test]").expect("writing to String cannot fail");
    writeln!(generated, "fn {test_name}() {{").expect("writing to String cannot fail");
    match config_index {
        Some(config_index) => writeln!(
            generated,
            "    run_submodule_compiler_baseline_config({test_type}, {relative_path:?}, Some({config_index}));"
        )
        .expect("writing to String cannot fail"),
        None => writeln!(
            generated,
            "    run_submodule_compiler_baseline_config({test_type}, {relative_path:?}, None);"
        )
        .expect("writing to String cannot fail"),
    }
    writeln!(generated, "}}\n").expect("writing to String cannot fail");
    Ok(())
}

fn enumerate_test_files(root: &Path, path: &Path, files: &mut Vec<String>) -> io::Result<()> {
    for entry in fs::read_dir(path)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            enumerate_test_files(root, &path, files)?;
        } else if path
            .extension()
            .and_then(|extension| extension.to_str())
            .is_some_and(|extension| extension == "ts" || extension == "tsx")
        {
            let relative = path.strip_prefix(root).expect("path is under root");
            files.push(relative.to_string_lossy().replace('\\', "/"));
        }
    }
    Ok(())
}

fn test_name(suite_name: &str, relative_path: &str, config_name: &str) -> String {
    let mut name = String::from("test_");
    name.push_str(suite_name);
    push_separator(&mut name);
    for byte in relative_path.bytes() {
        if byte.is_ascii_alphanumeric() {
            name.push((byte as char).to_ascii_lowercase());
        } else {
            push_separator(&mut name);
        }
    }
    if !config_name.is_empty() {
        push_separator(&mut name);
        for byte in config_name.bytes() {
            if byte.is_ascii_alphanumeric() {
                name.push((byte as char).to_ascii_lowercase());
            } else {
                push_separator(&mut name);
            }
        }
    }
    push_separator(&mut name);
    let mut hash_input = relative_path.as_bytes().to_vec();
    hash_input.push(0);
    hash_input.extend(config_name.as_bytes());
    name.push_str(&format!("{:016x}", fnv1a(&hash_input)));
    name
}

fn push_separator(name: &mut String) {
    if !name.ends_with('_') {
        name.push('_');
    }
}

fn fnv1a(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf29ce484222325;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

type TestConfiguration = HashMap<String, String>;

fn extract_compiler_settings(content: &str) -> HashMap<String, String> {
    let mut opts = HashMap::new();
    for line in split_lines(content) {
        if let Some((name, value)) = parse_option_line(line) {
            opts.insert(
                name.to_ascii_lowercase(),
                value.trim().trim_end_matches(';').to_string(),
            );
        }
    }
    opts
}

fn split_lines(content: &str) -> Vec<&str> {
    let mut lines = Vec::new();
    let mut start = 0;
    let bytes = content.as_bytes();
    let mut index = 0;
    while index < bytes.len() {
        match bytes[index] {
            b'\r' => {
                lines.push(&content[start..index]);
                index += 1;
                if index < bytes.len() && bytes[index] == b'\n' {
                    index += 1;
                }
                start = index;
            }
            b'\n' => {
                lines.push(&content[start..index]);
                index += 1;
                start = index;
            }
            _ => index += 1,
        }
    }
    lines.push(&content[start..]);
    lines
}

fn parse_option_line(line: &str) -> Option<(String, String)> {
    let line = line.trim_start();
    let rest = line.strip_prefix("//")?.trim_start();
    let rest = rest.strip_prefix('@')?;
    let (name, value) = rest.split_once(':')?;
    let name = name.trim();
    if name.is_empty()
        || !name
            .chars()
            .all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
    {
        return None;
    }
    Some((name.to_string(), value.to_string()))
}

fn file_based_test_configurations(settings: &HashMap<String, String>) -> Vec<String> {
    let vary_by_options = compiler_vary_by_map();
    let mut option_entries = Vec::new();
    let mut variation_count = 1;
    let mut non_varying_options = TestConfiguration::new();
    for (option, value) in settings {
        if vary_by_options.contains_key(&option.to_ascii_lowercase()) {
            let values = split_option_values(value, option);
            if values.len() > 1 {
                variation_count *= values.len();
                if variation_count > 25 {
                    panic!("Provided test options exceeded the maximum number of variations");
                }
                let mut entries = Vec::with_capacity(values.len() + 1);
                entries.push(option.clone());
                entries.extend(values);
                option_entries.push(entries);
            } else if values.len() == 1 {
                non_varying_options.insert(option.clone(), values[0].clone());
            }
        } else {
            non_varying_options.insert(option.clone(), value.clone());
        }
    }

    if !option_entries.is_empty() {
        option_entries.sort_by(|a, b| a[0].cmp(&b[0]));
        let mut variations = Vec::with_capacity(variation_count);
        compute_config_variations(
            &option_entries,
            0,
            TestConfiguration::new(),
            &mut variations,
        );
        return variations
            .into_iter()
            .map(|variation| config_description(&variation))
            .collect();
    }

    if !non_varying_options.is_empty() {
        return vec![String::new()];
    }

    Vec::new()
}

fn compute_config_variations(
    option_entries: &[Vec<String>],
    index: usize,
    current: TestConfiguration,
    out: &mut Vec<TestConfiguration>,
) {
    if index >= option_entries.len() {
        out.push(current);
        return;
    }
    let Some((option_key, entries)) = option_entries[index].split_first() else {
        return;
    };
    for entry in entries {
        let mut next = current.clone();
        next.insert(option_key.clone(), entry.clone());
        compute_config_variations(option_entries, index + 1, next, out);
    }
}

fn config_description(config: &TestConfiguration) -> String {
    let mut entries = config.iter().collect::<Vec<_>>();
    entries.sort_by_key(|(key, _)| key.as_str());
    entries
        .into_iter()
        .map(|(key, value)| format!("{key}={}", value.to_ascii_lowercase()))
        .collect::<Vec<_>>()
        .join(",")
}

fn split_option_values(value: &str, option: &str) -> Vec<String> {
    let mut star = false;
    let mut includes = Vec::new();
    let mut excludes = Vec::new();

    for entry in value
        .split(',')
        .map(str::trim)
        .filter(|entry| !entry.is_empty())
    {
        if entry == "*" {
            star = true;
        } else if let Some(exclude) = entry.strip_prefix('-').or_else(|| entry.strip_prefix('!')) {
            excludes.push(exclude.to_string());
        } else {
            includes.push(entry.trim_start_matches('+').to_string());
        }
    }

    if includes.is_empty() && !star && excludes.is_empty() {
        return Vec::new();
    }

    let mut variations = Vec::<(ts_tsoptions::CompilerOptionsValue, String)>::new();
    for include in includes {
        let parsed = value_of_option_string(option, &include);
        if !variations.iter().any(|(existing, _)| *existing == parsed) {
            variations.push((parsed, include));
        }
    }

    if star {
        for include in all_values_for_option(option) {
            let parsed = value_of_option_string(option, &include);
            if !variations.iter().any(|(existing, _)| *existing == parsed) {
                variations.push((parsed, include));
            }
        }
    }

    for exclude in excludes {
        if let Some(parsed) = try_value_of_option_string(option, &exclude) {
            variations.retain(|(value, _)| *value != parsed);
        }
    }

    if variations.is_empty() {
        panic!("Variations in test option '@{option}' resulted in an empty set.");
    }
    variations.into_iter().map(|(_, value)| value).collect()
}

fn value_of_option_string(option: &str, value: &str) -> ts_tsoptions::CompilerOptionsValue {
    try_value_of_option_string(option, value)
        .unwrap_or_else(|| panic!("Unknown value '{value}' for option '{option}'"))
}

fn try_value_of_option_string(
    option: &str,
    value: &str,
) -> Option<ts_tsoptions::CompilerOptionsValue> {
    let option_decl = command_line_option(option)?;
    match option_decl.kind {
        Some(ts_tsoptions::CommandLineOptionKind::Enum) => option_decl
            .enum_map()?
            .get(&value.to_ascii_lowercase())
            .cloned(),
        Some(ts_tsoptions::CommandLineOptionKind::Boolean) => {
            match value.to_ascii_lowercase().as_str() {
                "true" => Some(ts_tsoptions::CompilerOptionsValue::Bool(true)),
                "false" => Some(ts_tsoptions::CompilerOptionsValue::Bool(false)),
                _ => None,
            }
        }
        Some(ts_tsoptions::CommandLineOptionKind::Number) => value
            .parse::<i32>()
            .ok()
            .map(ts_tsoptions::CompilerOptionsValue::Number),
        _ => Some(ts_tsoptions::CompilerOptionsValue::String(
            value.to_string(),
        )),
    }
}

fn command_line_option(option: &str) -> Option<ts_tsoptions::CommandLineOption> {
    compiler_option_declarations()
        .into_iter()
        .find(|option_decl| option_decl.name.eq_ignore_ascii_case(option))
}

fn all_values_for_option(option: &str) -> Vec<String> {
    let Some(option_decl) = command_line_option(option) else {
        return Vec::new();
    };
    match option_decl.kind {
        Some(ts_tsoptions::CommandLineOptionKind::Enum) => {
            ts_tsoptions::enum_keys(&option_decl.name).unwrap_or_default()
        }
        Some(ts_tsoptions::CommandLineOptionKind::Boolean) => {
            vec!["true".to_string(), "false".to_string()]
        }
        _ => Vec::new(),
    }
}

fn compiler_option_declarations() -> Vec<ts_tsoptions::CommandLineOption> {
    let mut options = ts_tsoptions::options_declarations().to_vec();
    options.extend([
        ts_tsoptions::CommandLineOption::new(
            "allowNonTsExtensions",
            ts_tsoptions::CommandLineOptionKind::Boolean,
        ),
        ts_tsoptions::CommandLineOption::new(
            "noErrorTruncation",
            ts_tsoptions::CommandLineOptionKind::Boolean,
        ),
        ts_tsoptions::CommandLineOption::new(
            "suppressOutputPathCheck",
            ts_tsoptions::CommandLineOptionKind::Boolean,
        ),
        ts_tsoptions::CommandLineOption::new(
            "noCheck",
            ts_tsoptions::CommandLineOptionKind::Boolean,
        ),
    ]);
    options
}

fn compiler_vary_by_map() -> HashMap<String, ()> {
    let mut vary_by_map = HashMap::new();
    for option in ts_tsoptions::options_declarations() {
        let is_boolean_or_enum = matches!(
            option.kind,
            Some(
                ts_tsoptions::CommandLineOptionKind::Boolean
                    | ts_tsoptions::CommandLineOptionKind::Enum
            )
        );
        if !option.is_command_line_only
            && is_boolean_or_enum
            && (option.affects_program_structure
                || option.affects_emit
                || option.affects_module_resolution
                || option.affects_bind_diagnostics
                || option.affects_semantic_diagnostics
                || option.affects_source_file
                || option.affects_declaration_path
                || option.affects_build_info)
        {
            vary_by_map.insert(option.name.to_ascii_lowercase(), ());
        }
    }
    vary_by_map.insert("noemit".to_string(), ());
    vary_by_map.insert("isolatedmodules".to_string(), ());
    vary_by_map
}

fn decode_bytes(bytes: &[u8]) -> Option<String> {
    if bytes.starts_with(&[0xEF, 0xBB, 0xBF]) {
        return String::from_utf8(bytes[3..].to_vec()).ok();
    }
    if bytes.starts_with(&[0xFF, 0xFE]) {
        return decode_utf16(&bytes[2..], true);
    }
    if bytes.starts_with(&[0xFE, 0xFF]) {
        return decode_utf16(&bytes[2..], false);
    }
    String::from_utf8(bytes.to_vec()).ok()
}

fn decode_utf16(bytes: &[u8], little_endian: bool) -> Option<String> {
    let words = bytes
        .chunks_exact(2)
        .map(|chunk| {
            if little_endian {
                u16::from_le_bytes([chunk[0], chunk[1]])
            } else {
                u16::from_be_bytes([chunk[0], chunk[1]])
            }
        })
        .collect::<Vec<_>>();
    String::from_utf16(&words).ok()
}
