// Code generated by moq; ported to Rust. DO NOT EDIT.

use std::io;
use std::sync::{Arc, Mutex};
use std::time::SystemTime;

use crate::vfs::{Entries, FileInfo, Fs};

type AppendFileFunc = dyn Fn(&str, &str) -> io::Result<()> + Send + Sync;
type ChtimesFunc = dyn Fn(&str, SystemTime, SystemTime) -> io::Result<()> + Send + Sync;
type PathBoolFunc = dyn Fn(&str) -> bool + Send + Sync;
type EntriesFunc = dyn Fn(&str) -> Entries + Send + Sync;
type ReadFileFunc = dyn Fn(&str) -> (String, bool) + Send + Sync;
type RealpathFunc = dyn Fn(&str) -> String + Send + Sync;
type PathResultFunc = dyn Fn(&str) -> io::Result<()> + Send + Sync;
type StatFunc = dyn Fn(&str) -> io::Result<FileInfo> + Send + Sync;
type UseCaseSensitiveFileNamesFunc = dyn Fn() -> bool + Send + Sync;
type WalkDirFunc =
    dyn for<'a> Fn(&str, &mut crate::WalkDirFunc<'a>) -> io::Result<()> + Send + Sync;
type WriteFileFunc = dyn Fn(&str, &str) -> io::Result<()> + Send + Sync;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PathCall {
    pub path: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DataCall {
    pub path: String,
    pub data: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ChtimesCall {
    pub path: String,
    pub atime: SystemTime,
    pub mtime: SystemTime,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WalkDirCall {
    pub root: String,
}

#[derive(Clone, Debug, Default)]
pub(crate) struct Calls {
    append_file: Vec<DataCall>,
    chtimes: Vec<ChtimesCall>,
    directory_exists: Vec<PathCall>,
    file_exists: Vec<PathCall>,
    get_accessible_entries: Vec<PathCall>,
    read_file: Vec<PathCall>,
    realpath: Vec<PathCall>,
    remove: Vec<PathCall>,
    stat: Vec<PathCall>,
    use_case_sensitive_file_names: Vec<()>,
    walk_dir: Vec<WalkDirCall>,
    write_file: Vec<DataCall>,
}

#[derive(Clone, Default)]
pub struct FsMock {
    pub append_file_func: Option<Arc<AppendFileFunc>>,
    pub chtimes_func: Option<Arc<ChtimesFunc>>,
    pub directory_exists_func: Option<Arc<PathBoolFunc>>,
    pub file_exists_func: Option<Arc<PathBoolFunc>>,
    pub get_accessible_entries_func: Option<Arc<EntriesFunc>>,
    pub read_file_func: Option<Arc<ReadFileFunc>>,
    pub realpath_func: Option<Arc<RealpathFunc>>,
    pub remove_func: Option<Arc<PathResultFunc>>,
    pub stat_func: Option<Arc<StatFunc>>,
    pub use_case_sensitive_file_names_func: Option<Arc<UseCaseSensitiveFileNamesFunc>>,
    pub walk_dir_func: Option<Arc<WalkDirFunc>>,
    pub write_file_func: Option<Arc<WriteFileFunc>>,
    pub(crate) calls: Arc<Mutex<Calls>>,
}

impl FsMock {
    pub fn append_file_calls(&self) -> Vec<DataCall> {
        self.calls.lock().unwrap().append_file.clone()
    }

    pub fn chtimes_calls(&self) -> Vec<ChtimesCall> {
        self.calls.lock().unwrap().chtimes.clone()
    }

    pub fn directory_exists_calls(&self) -> Vec<PathCall> {
        self.calls.lock().unwrap().directory_exists.clone()
    }

    pub fn file_exists_calls(&self) -> Vec<PathCall> {
        self.calls.lock().unwrap().file_exists.clone()
    }

    pub fn get_accessible_entries_calls(&self) -> Vec<PathCall> {
        self.calls.lock().unwrap().get_accessible_entries.clone()
    }

    pub fn read_file_calls(&self) -> Vec<PathCall> {
        self.calls.lock().unwrap().read_file.clone()
    }

    pub fn realpath_calls(&self) -> Vec<PathCall> {
        self.calls.lock().unwrap().realpath.clone()
    }

    pub fn remove_calls(&self) -> Vec<PathCall> {
        self.calls.lock().unwrap().remove.clone()
    }

    pub fn stat_calls(&self) -> Vec<PathCall> {
        self.calls.lock().unwrap().stat.clone()
    }

    pub fn use_case_sensitive_file_names_calls(&self) -> Vec<()> {
        self.calls
            .lock()
            .unwrap()
            .use_case_sensitive_file_names
            .clone()
    }

    pub fn walk_dir_calls(&self) -> Vec<WalkDirCall> {
        self.calls.lock().unwrap().walk_dir.clone()
    }

    pub fn write_file_calls(&self) -> Vec<DataCall> {
        self.calls.lock().unwrap().write_file.clone()
    }
}

impl Fs for FsMock {
    fn append_file(&self, path: &str, data: &str) -> io::Result<()> {
        self.calls.lock().unwrap().append_file.push(DataCall {
            path: path.to_owned(),
            data: data.to_owned(),
        });
        let Some(func) = &self.append_file_func else {
            panic!("FsMock.append_file_func: method is nil but Fs.append_file was just called");
        };
        func(path, data)
    }

    fn chtimes(&self, path: &str, atime: SystemTime, mtime: SystemTime) -> io::Result<()> {
        self.calls.lock().unwrap().chtimes.push(ChtimesCall {
            path: path.to_owned(),
            atime,
            mtime,
        });
        let Some(func) = &self.chtimes_func else {
            panic!("FsMock.chtimes_func: method is nil but Fs.chtimes was just called");
        };
        func(path, atime, mtime)
    }

    fn directory_exists(&self, path: &str) -> bool {
        self.calls.lock().unwrap().directory_exists.push(PathCall {
            path: path.to_owned(),
        });
        let Some(func) = &self.directory_exists_func else {
            panic!(
                "FsMock.directory_exists_func: method is nil but Fs.directory_exists was just called"
            );
        };
        func(path)
    }

    fn file_exists(&self, path: &str) -> bool {
        self.calls.lock().unwrap().file_exists.push(PathCall {
            path: path.to_owned(),
        });
        let Some(func) = &self.file_exists_func else {
            panic!("FsMock.file_exists_func: method is nil but Fs.file_exists was just called");
        };
        func(path)
    }

    fn get_accessible_entries(&self, path: &str) -> Entries {
        self.calls
            .lock()
            .unwrap()
            .get_accessible_entries
            .push(PathCall {
                path: path.to_owned(),
            });
        let Some(func) = &self.get_accessible_entries_func else {
            panic!(
                "FsMock.get_accessible_entries_func: method is nil but Fs.get_accessible_entries was just called"
            );
        };
        func(path)
    }

    fn read_file(&self, path: &str) -> (String, bool) {
        self.calls.lock().unwrap().read_file.push(PathCall {
            path: path.to_owned(),
        });
        let Some(func) = &self.read_file_func else {
            panic!("FsMock.read_file_func: method is nil but Fs.read_file was just called");
        };
        func(path)
    }

    fn realpath(&self, path: &str) -> String {
        self.calls.lock().unwrap().realpath.push(PathCall {
            path: path.to_owned(),
        });
        let Some(func) = &self.realpath_func else {
            panic!("FsMock.realpath_func: method is nil but Fs.realpath was just called");
        };
        func(path)
    }

    fn remove(&self, path: &str) -> io::Result<()> {
        self.calls.lock().unwrap().remove.push(PathCall {
            path: path.to_owned(),
        });
        let Some(func) = &self.remove_func else {
            panic!("FsMock.remove_func: method is nil but Fs.remove was just called");
        };
        func(path)
    }

    fn stat(&self, path: &str) -> io::Result<FileInfo> {
        self.calls.lock().unwrap().stat.push(PathCall {
            path: path.to_owned(),
        });
        let Some(func) = &self.stat_func else {
            panic!("FsMock.stat_func: method is nil but Fs.stat was just called");
        };
        func(path)
    }

    fn use_case_sensitive_file_names(&self) -> bool {
        self.calls
            .lock()
            .unwrap()
            .use_case_sensitive_file_names
            .push(());
        let Some(func) = &self.use_case_sensitive_file_names_func else {
            panic!(
                "FsMock.use_case_sensitive_file_names_func: method is nil but Fs.use_case_sensitive_file_names was just called"
            );
        };
        func()
    }

    fn walk_dir(&self, root: &str, walk_fn: &mut crate::WalkDirFunc<'_>) -> io::Result<()> {
        self.calls.lock().unwrap().walk_dir.push(WalkDirCall {
            root: root.to_owned(),
        });
        let Some(func) = &self.walk_dir_func else {
            panic!("FsMock.walk_dir_func: method is nil but Fs.walk_dir was just called");
        };
        func(root, walk_fn)
    }

    fn write_file(&self, path: &str, data: &str) -> io::Result<()> {
        self.calls.lock().unwrap().write_file.push(DataCall {
            path: path.to_owned(),
            data: data.to_owned(),
        });
        let Some(func) = &self.write_file_func else {
            panic!("FsMock.write_file_func: method is nil but Fs.write_file was just called");
        };
        func(path, data)
    }
}

// PORT STATUS
//   source:     internal/vfs/vfsmock/mock_generated.go (generated)
//   confidence: medium
//   todos:      none tracked
//   notes:      Generated Go method fields and call tracking are represented with Arc<dyn Fn> callbacks.
