#![forbid(unsafe_code)]
mod baseproto;
#[cfg(test)]
mod baseproto_test;
mod jsonrpc;
mod lsp;
#[cfg(test)]
mod lsp_json_test;
#[cfg(test)]
mod lsp_test;
mod util;

pub use baseproto::{BaseReader, BaseWriter, new_base_reader, new_base_writer};
pub use jsonrpc::{Message, RequestMessage, ResponseMessage, new_id};
pub use lsp::{
    AddAsTypeOnly, ApplyKind, ApplyKindMerge, ApplyKindReplace, ApplyWorkspaceEditParams,
    ApplyWorkspaceEditResult, ApplyWorkspaceEditResultOrNull, AutoImportFix, AutoImportFixKind,
    CallHierarchyIncomingCall, CallHierarchyIncomingCallsOrNull, CallHierarchyIncomingCallsParams,
    CallHierarchyItem, CallHierarchyItemsOrNull, CallHierarchyOutgoingCall,
    CallHierarchyOutgoingCallsOrNull, CallHierarchyOutgoingCallsParams, CallHierarchyPrepareParams,
    CancelParams, ClientCapabilities, ClientCapabilitiesExt, ClientInfo, CodeAction,
    CodeActionContext, CodeActionDisabled, CodeActionKind, CodeActionKindSourceRemoveUnusedImports,
    CodeActionKindSourceSortImports, CodeActionOrNull, CodeActionParams, CodeActionTag,
    CodeActionTriggerKind, CodeLens, CodeLensData, CodeLensKind, CodeLensOrNull, CodeLensParams,
    CodeLensesOrNull, Color, ColorInformation, ColorPresentation, Command, CommandOrCodeAction,
    CommandOrCodeActionArrayOrNull, CompletionContext, CompletionItem, CompletionItemApplyKinds,
    CompletionItemData, CompletionItemDefaults, CompletionItemKind, CompletionItemLabelDetails,
    CompletionItemOrNull, CompletionItemTag, CompletionItemsOrListOrNull, CompletionList,
    CompletionParams, CompletionTextEdit, CreateFile, CreateFilesParams, CustomProjectInfoInfo,
    CustomRunGCInfo, CustomSaveAllocProfileInfo, CustomSaveHeapProfileInfo,
    CustomStartCPUProfileInfo, CustomStopCPUProfileInfo, DeclarationParams, DefinitionParams,
    DeleteFile, DeleteFilesParams, Diagnostic, DiagnosticRelatedInformation, DiagnosticSeverity,
    DiagnosticTag, DidChangeConfigurationParams, DidChangeTextDocumentParams,
    DidChangeWatchedFilesParams, DidChangeWorkspaceFoldersParams, DidCloseTextDocumentParams,
    DidOpenTextDocumentParams, DidSaveTextDocumentParams, DocumentDiagnosticParams,
    DocumentFormattingParams, DocumentHighlight, DocumentHighlightKind, DocumentHighlightParams,
    DocumentHighlightsOrNull, DocumentLink, DocumentLinkOrNull, DocumentLinkParams,
    DocumentLinksOrNull, DocumentOnTypeFormattingParams, DocumentRangeFormattingParams,
    DocumentRangesFormattingParams, DocumentSymbol, DocumentSymbolParams, DocumentUri,
    DocumentUriExt, Documentation, EditRangeWithInsertReplace, ErrorCode, ErrorCodeContentModified,
    ErrorCodeInternalError, ErrorCodeInvalidParams, ErrorCodeInvalidRequest,
    ErrorCodeMethodNotFound, ErrorCodeParseError, ErrorCodeRequestCancelled,
    ErrorCodeRequestFailed, ErrorCodeServerCancelled, ErrorCodeServerNotInitialized,
    ErrorCodeUnknownErrorCode, ExecuteCommandParams, FileChangeType, FileCreate, FileDelete,
    FileEvent, FileOperationFilter, FileOperationPattern, FileRename, FileSystemWatcher,
    FoldingRange, FoldingRangeKind, FoldingRangesOrNull, FullDocumentDiagnosticReport,
    FullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport, GlobPattern, HasLocation,
    HasLocations, HasTextDocumentPosition, HasTextDocumentUri, Hover, HoverContents, HoverOrNull,
    HoverParams, ImplementationParams, ImportKind, InitializationOptions,
    InitializeAPISessionParams, InitializeAPISessionResultOrNull, InitializeInfo, InitializeParams,
    InitializeResult, InitializeResultOrNull, InitializedInfo, InitializedParams, InlayHint,
    InlayHintKind, InlayHintLabel, InlayHintLabelPart, InlayHintOrNull, InlayHintParams,
    InlayHintTooltip, InlayHintsOrNull, InlineCompletionListOrItemsOrNull, InlineCompletionParams,
    InlineValueParams, InlineValuesOrNull, InsertReplaceEdit, InsertTextFormat, IntegerOrString,
    LSPAny, LSPAnyOrNull, LanguageKind, LinkedEditingRangeParams, LinkedEditingRanges,
    LinkedEditingRangesOrNull, Location, LocationLink, LocationOrLocationUriOnly,
    LocationOrLocationsOrDefinitionLinksOrNull, LocationUriOnly, LocationsOrNull, LogMessageParams,
    LogTraceParams, METHOD_WINDOW_LOG_MESSAGE, MarkedStringWithLanguage, MarkupContent,
    MarkupContentOrStringOrMarkedStringWithLanguageOrMarkedStrings, MarkupKind,
    MarkupKindPlainText, MessageActionItemOrNull, MessageType, Method,
    MethodCallHierarchyIncomingCalls, MethodCallHierarchyOutgoingCalls, MethodCancelRequest,
    MethodClientRegisterCapability, MethodClientUnregisterCapability,
    MethodCustomInitializeAPISession, MethodCustomProjectInfo, MethodCustomRunGC,
    MethodCustomSaveAllocProfile, MethodCustomSaveHeapProfile, MethodCustomStartCPUProfile,
    MethodCustomStopCPUProfile, MethodCustomTextDocumentMultiDocumentHighlight,
    MethodCustomTextDocumentSourceDefinition, MethodExit, MethodInitialize, MethodInitialized,
    MethodLogTrace, MethodProgress, MethodSetTrace, MethodShutdown, MethodTelemetryEvent,
    MethodTextDocumentCodeAction, MethodTextDocumentCodeLens, MethodTextDocumentCompletion,
    MethodTextDocumentDeclaration, MethodTextDocumentDefinition, MethodTextDocumentDiagnostic,
    MethodTextDocumentDidChange, MethodTextDocumentDidClose, MethodTextDocumentDidOpen,
    MethodTextDocumentDidSave, MethodTextDocumentDocumentHighlight, MethodTextDocumentDocumentLink,
    MethodTextDocumentDocumentSymbol, MethodTextDocumentFormatting, MethodTextDocumentHover,
    MethodTextDocumentImplementation, MethodTextDocumentInlayHint,
    MethodTextDocumentInlineCompletion, MethodTextDocumentInlineValue,
    MethodTextDocumentLinkedEditingRange, MethodTextDocumentMoniker,
    MethodTextDocumentOnTypeFormatting, MethodTextDocumentPrepareCallHierarchy,
    MethodTextDocumentPrepareRename, MethodTextDocumentPrepareTypeHierarchy,
    MethodTextDocumentPublishDiagnostics, MethodTextDocumentRangeFormatting,
    MethodTextDocumentRangesFormatting, MethodTextDocumentReferences, MethodTextDocumentRename,
    MethodTextDocumentSelectionRange, MethodTextDocumentSemanticTokensFull,
    MethodTextDocumentSemanticTokensFullDelta, MethodTextDocumentSemanticTokensRange,
    MethodTextDocumentSignatureHelp, MethodTextDocumentTypeDefinition,
    MethodTextDocumentVSOnAutoInsert, MethodTextDocumentWillSave,
    MethodTextDocumentWillSaveWaitUntil, MethodTypeHierarchySubtypes,
    MethodTypeHierarchySupertypes, MethodWindowLogMessage, MethodWindowShowDocument,
    MethodWindowShowMessage, MethodWindowWorkDoneProgressCancel, MethodWorkspaceApplyEdit,
    MethodWorkspaceCodeLensRefresh, MethodWorkspaceDiagnostic, MethodWorkspaceDiagnosticRefresh,
    MethodWorkspaceDidChangeConfiguration, MethodWorkspaceDidChangeWatchedFiles,
    MethodWorkspaceDidChangeWorkspaceFolders, MethodWorkspaceDidCreateFiles,
    MethodWorkspaceDidDeleteFiles, MethodWorkspaceDidRenameFiles, MethodWorkspaceExecuteCommand,
    MethodWorkspaceFoldingRangeRefresh, MethodWorkspaceInlayHintRefresh,
    MethodWorkspaceInlineValueRefresh, MethodWorkspaceSemanticTokensRefresh, MethodWorkspaceSymbol,
    MethodWorkspaceTextDocumentContent, MethodWorkspaceTextDocumentContentRefresh,
    MethodWorkspaceWillCreateFiles, MethodWorkspaceWillDeleteFiles, MethodWorkspaceWillRenameFiles,
    MonikersOrNull, MultiDocumentHighlightParams, MultiDocumentHighlightsOrNull, NoParams,
    NotificationInfo, Null, OneOf, OptionalVersionedTextDocumentIdentifier, ParameterInformation,
    Pattern, PerformanceStatsTelemetryEvent, PerformanceStatsTelemetryMeasurements,
    PositionEncodingKind, PositionEncodingKindUTF8, PositionEncodingKindUTF16,
    PositionEncodingKindUTF32, PrepareRenameDefaultBehavior, PrepareRenameParams,
    PrepareRenamePlaceholder, ProfileParams, ProfileResult, ProfileResultOrNull, ProgressInfo,
    ProgressParams, ProjectInfoParams, ProjectInfoResultOrNull, ProjectInfoTelemetryEvent,
    ProjectInfoTelemetryMeasurements, PublishDiagnosticsParams, RangeOrEditRangeWithInsertReplace,
    RangeOrPrepareRenamePlaceholderOrPrepareRenameDefaultBehaviorOrNull, ReferenceContext,
    ReferenceParams, RegistrationParams, RelatedFullDocumentDiagnosticReport,
    RelatedFullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport,
    RelatedUnchangedDocumentDiagnosticReport, RelativePattern, RenameFile, RenameFilesParams,
    RenameParams, RequestFailureTelemetryEvent, RequestFailureTelemetryProperties, RequestInfo,
    ResolvedClientCapabilities, ResolvedCompletionClientCapabilities,
    ResolvedCompletionItemClientCapabilities, ResolvedCompletionListClientCapabilities,
    ResolvedDiagnosticClientCapabilities, ResolvedDocumentSymbolClientCapabilities,
    ResolvedFoldingRangeClientCapabilities, ResolvedFoldingRangeClientCapabilitiesInner,
    ResolvedGeneralClientCapabilities, ResolvedGotoClientCapabilities,
    ResolvedHoverClientCapabilities, ResolvedSemanticTokensClientCapabilities,
    ResolvedSignatureHelpClientCapabilities, ResolvedSignatureInformationClientCapabilities,
    ResolvedTagSupport, ResolvedTextDocumentClientCapabilities, ResolvedWindowClientCapabilities,
    ResolvedWorkspaceClientCapabilities, ResolvedWorkspaceEditClientCapabilities,
    ResolvedWorkspaceFileOperationsClientCapabilities, ResourceOperationKind, RunGCResponse,
    SaveAllocProfileResponse, SaveHeapProfileResponse, SelectionRange, SelectionRangeParams,
    SelectionRangesOrNull, SemanticTokenModifier, SemanticTokenType, SemanticTokens,
    SemanticTokensDelta, SemanticTokensDeltaParams, SemanticTokensLegend, SemanticTokensOrNull,
    SemanticTokensOrSemanticTokensDeltaOrNull, SemanticTokensParams, SemanticTokensRangeParams,
    ServerCapabilities, ServerInfo, SetTraceParams, ShowDocumentParams, ShowDocumentResult,
    ShowDocumentResultOrNull, ShowMessageParams, SignatureHelp, SignatureHelpContext,
    SignatureHelpOrNull, SignatureHelpParams, SignatureHelpResponse, SignatureHelpTriggerKind,
    SignatureInformation, StartCPUProfileResponse, StopCPUProfileResponse, StringLiteralFull,
    StringLiteralRename, StringLiteralUnchanged, StringOrInlayHintLabelParts,
    StringOrMarkedStringWithLanguage, StringOrMarkupContent, StringOrTuple, SymbolInformation,
    SymbolInformationsOrDocumentSymbolsOrNull, SymbolInformationsOrWorkspaceSymbolsOrNull,
    SymbolKind, SymbolKindClass, SymbolKindConstructor, SymbolKindEnum, SymbolKindEnumMember,
    SymbolKindFile, SymbolKindFunction, SymbolKindInterface, SymbolKindMethod, SymbolKindModule,
    SymbolKindNamespace, SymbolKindObject, SymbolKindPackage, SymbolKindProperty, SymbolKindString,
    SymbolKindTypeParameter, SymbolKindVariable, TelemetryEvent, TelemetryEventInfo,
    TextDocumentCodeActionInfo, TextDocumentCompletionInfo, TextDocumentContentChangePartial,
    TextDocumentContentChangePartialOrWholeDocument, TextDocumentContentChangeWholeDocument,
    TextDocumentContentParams, TextDocumentContentRefreshParams, TextDocumentContentResultOrNull,
    TextDocumentDiagnosticInfo, TextDocumentDidChangeInfo, TextDocumentDidCloseInfo,
    TextDocumentDidOpenInfo, TextDocumentDocumentSymbolInfo, TextDocumentEdit,
    TextDocumentEditOrCreateFileOrRenameFileOrDeleteFile, TextDocumentFormattingInfo,
    TextDocumentHoverInfo, TextDocumentIdentifier, TextDocumentItem,
    TextDocumentOnTypeFormattingInfo, TextDocumentPositionParams, TextDocumentRangeFormattingInfo,
    TextDocumentReferencesInfo, TextDocumentSemanticTokensFullInfo, TextEdit,
    TextEditOrAnnotatedTextEditOrSnippetTextEdit, TextEditOrInsertReplaceEdit, TextEditsOrNull,
    TraceValue, TypeDefinitionParams, TypeHierarchyItemsOrNull, TypeHierarchyPrepareParams,
    TypeHierarchySubtypesParams, TypeHierarchySupertypesParams, UintegerOrNull,
    UnchangedDocumentDiagnosticReport, UnregistrationParams, Uri, VersionedTextDocumentIdentifier,
    VsOnAutoInsertParams, VsOnAutoInsertResponseItemOrNull, WatchKind, WillSaveTextDocumentParams,
    WindowClientCapabilities, WindowLogMessageInfo, WindowWorkDoneProgressCreateInfo,
    WorkDoneProgressBegin, WorkDoneProgressBeginOrReportOrEnd, WorkDoneProgressCancelParams,
    WorkDoneProgressCreateParams, WorkDoneProgressEnd, WorkDoneProgressOptions,
    WorkDoneProgressReport, WorkspaceDiagnosticParams, WorkspaceDiagnosticReport,
    WorkspaceDiagnosticReportOrNull, WorkspaceDidChangeConfigurationInfo,
    WorkspaceDidChangeWatchedFilesInfo, WorkspaceEdit, WorkspaceEditOrNull, WorkspaceFolder,
    WorkspaceFoldersChangeEvent, WorkspaceFoldersOrNull, WorkspaceFullDocumentDiagnosticReport,
    WorkspaceFullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport, WorkspaceSymbol,
    WorkspaceSymbolOrNull, WorkspaceSymbolParams, WorkspaceUnchangedDocumentDiagnosticReport,
    assert_at_most_one, assert_only_one, bool_to_int, err_invalid_kind, err_invalid_value,
    err_literal_mismatch, err_missing, err_not_object, err_null, fix_windows_uri_path,
    get_client_capabilities, json_key_check, json_object_has_key, json_object_raw_field,
    preferred_markup_kind, unmarshal_any, unmarshal_empty, unmarshal_params, unmarshal_ptr_to,
    unmarshal_result, unmarshal_value, with_client_capabilities,
};
pub use lsp::{
    ApplyWorkspaceEditResponse, CallHierarchyIncomingCallsResponse,
    CallHierarchyOutgoingCallsResponse, CallHierarchyPrepareResponse, CodeActionResolveParams,
    CodeActionResolveResponse, CodeActionResponse, CodeLensRefreshResponse, CodeLensResolveParams,
    CodeLensResolveResponse, CodeLensResponse, ColorPresentationParams, ColorPresentationResponse,
    CompletionResolveResponse, CompletionResponse, ConfigurationParams, ConfigurationResponse,
    CustomInitializeAPISessionResponse, CustomMultiDocumentHighlightResponse,
    CustomProjectInfoResponse, CustomTextDocumentSourceDefinitionResponse, DeclarationResponse,
    DefinitionResponse, DiagnosticRefreshResponse, DocumentColorParams, DocumentColorResponse,
    DocumentDiagnosticResponse, DocumentFormattingResponse, DocumentHighlightResponse,
    DocumentLinkResolveParams, DocumentLinkResolveResponse, DocumentLinkResponse,
    DocumentOnTypeFormattingResponse, DocumentRangeFormattingResponse,
    DocumentRangesFormattingResponse, DocumentSymbolResponse, ExecuteCommandResponse,
    FoldingRangeParams, FoldingRangeRefreshResponse, FoldingRangeResponse, HoverResponse,
    ImplementationResponse, InitializeAPISessionResult, InitializeResponse,
    InlayHintRefreshResponse, InlayHintResolveResponse, InlayHintResponse,
    InlineCompletionResponse, InlineCompletionWireResponse, InlineValueRefreshResponse,
    InlineValueResponse, LinkedEditingRangeResponse, MethodCodeActionResolve,
    MethodCodeLensResolve, MethodCompletionItemResolve, MethodDocumentLinkResolve,
    MethodInlayHintResolve, MethodTextDocumentColorPresentation, MethodTextDocumentDocumentColor,
    MethodTextDocumentFoldingRange, MethodWindowShowMessageRequest,
    MethodWindowWorkDoneProgressCreate, MethodWorkspaceConfiguration, MethodWorkspaceSymbolResolve,
    MethodWorkspaceWorkspaceFolders, MonikerResponse, MultiDocumentHighlight,
    PrepareRenameResponse, ProjectInfoResult, ReferencesResponse, RegistrationResponse,
    RenameResponse, SelectionRangeResponse, SemanticTokensDeltaResponse,
    SemanticTokensRangeResponse, SemanticTokensRefreshResponse, SemanticTokensResponse,
    ShowDocumentResponse, ShowMessageRequestParams, ShowMessageResponse, ShutdownResponse,
    TextDocumentContentRefreshResponse, TextDocumentContentResponse, TextDocumentContentResult,
    TypeDefinitionResponse, TypeHierarchyPrepareResponse, TypeHierarchySubtypesResponse,
    TypeHierarchySupertypesResponse, UnregistrationResponse, VsOnAutoInsertResponse,
    VsOnAutoInsertResponseItem, WillCreateFilesResponse, WillDeleteFilesResponse,
    WillRenameFilesResponse, WillSaveTextDocumentWaitUntilResponse, WorkspaceDiagnosticResponse,
    WorkspaceFoldersResponse, WorkspaceSymbolResolveParams, WorkspaceSymbolResolveResponse,
    WorkspaceSymbolResponse,
};
pub use lsp::{
    BooleanOrDefinitionOptions, BooleanOrHoverOptions, BooleanOrReferenceOptions,
    BooleanOrSaveOptions, ClientRegisterCapabilityInfo, ClientUnregisterCapabilityInfo,
    ConfigurationItem, DidChangeConfigurationRegistrationOptions,
    DidChangeWatchedFilesRegistrationOptions, FileOperationOptions,
    FileOperationRegistrationOptions, RegisterOptions, Registration, StringOrStrings,
    TextDocumentPublishDiagnosticsInfo, TextDocumentSyncKind, TextDocumentSyncOptions,
    TextDocumentSyncOptionsOrKind, Unregistration, WorkspaceCodeLensRefreshInfo,
    WorkspaceConfigurationInfo, WorkspaceDiagnosticRefreshInfo, WorkspaceInlayHintRefreshInfo,
    WorkspaceOptions,
};
pub use util::{FormattingOptions, Position, Range, compare_positions, compare_ranges};
