#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct GeneratedIdentifierFlags(pub i32);

impl GeneratedIdentifierFlags {
    // Kind

    /// Not automatically generated.
    pub const NONE: Self = Self(0);
    /// Automatically generated identifier.
    pub const AUTO: Self = Self(1);
    /// Automatically generated identifier with a preference for '_i'.
    pub const LOOP: Self = Self(2);
    /// Unique name based on the 'text' property.
    pub const UNIQUE: Self = Self(3);
    /// Unique name based on the node in the 'Node' property.
    pub const NODE: Self = Self(4);
    /// Mask to extract the kind of identifier from its flags.
    pub const KIND_MASK: Self = Self(7);

    // Flags

    /// Reserve the generated name in nested scopes.
    pub const RESERVED_IN_NESTED_SCOPES: Self = Self(1 << 3);
    /// First instance won't use '_#' if there's no conflict.
    pub const OPTIMISTIC: Self = Self(1 << 4);
    /// Use only the file identifiers list and not generated names to search for conflicts.
    pub const FILE_LEVEL: Self = Self(1 << 5);
    /// Used by `module.ts` to indicate generated nodes which can have substitutions performed upon them
    /// (as they were generated by an earlier transform phase).
    pub const ALLOW_NAME_SUBSTITUTION: Self = Self(1 << 6);

    pub const fn kind(self) -> Self {
        Self(self.0 & Self::KIND_MASK.0)
    }

    pub const fn is_auto(self) -> bool {
        self.kind().0 == Self::AUTO.0
    }

    pub const fn is_loop(self) -> bool {
        self.kind().0 == Self::LOOP.0
    }

    pub const fn is_unique(self) -> bool {
        self.kind().0 == Self::UNIQUE.0
    }

    pub const fn is_node(self) -> bool {
        self.kind().0 == Self::NODE.0
    }

    pub const fn is_reserved_in_nested_scopes(self) -> bool {
        self.0 & Self::RESERVED_IN_NESTED_SCOPES.0 != 0
    }

    pub const fn is_optimistic(self) -> bool {
        self.0 & Self::OPTIMISTIC.0 != 0
    }

    pub const fn is_file_level(self) -> bool {
        self.0 & Self::FILE_LEVEL.0 != 0
    }

    pub const fn has_allow_name_substitution(self) -> bool {
        self.0 & Self::ALLOW_NAME_SUBSTITUTION.0 != 0
    }
}

impl std::ops::BitOr for GeneratedIdentifierFlags {
    type Output = Self;

    fn bitor(self, rhs: Self) -> Self::Output {
        Self(self.0 | rhs.0)
    }
}

impl std::ops::BitOrAssign for GeneratedIdentifierFlags {
    fn bitor_assign(&mut self, rhs: Self) {
        self.0 |= rhs.0;
    }
}

impl std::ops::BitAnd for GeneratedIdentifierFlags {
    type Output = Self;

    fn bitand(self, rhs: Self) -> Self::Output {
        Self(self.0 & rhs.0)
    }
}

impl std::ops::Not for GeneratedIdentifierFlags {
    type Output = Self;

    fn not(self) -> Self::Output {
        Self(!self.0)
    }
}

// --------------------------------------------------------------------------
// PORT STATUS
//   source:     internal/printer/generatedidentifierflags.go (57 lines)
//   confidence: high
//   todos:      0
//   notes:      reviewed against Go; flag discriminants, masks, predicates,
//               and bit operations match the source constants. Rust adds
//               Default for the Go zero-value behavior.
// --------------------------------------------------------------------------
