// Code generated by "stringer -type=SignatureKind -output=stringer_generated.go"; DO NOT EDIT.

use crate::types::{SIGNATURE_KIND_CALL, SIGNATURE_KIND_CONSTRUCT, SignatureKind};

pub fn signature_kind_as_str(value: SignatureKind) -> Option<&'static str> {
    match value {
        SIGNATURE_KIND_CALL => Some("SignatureKindCall"),
        SIGNATURE_KIND_CONSTRUCT => Some("SignatureKindConstruct"),
        _ => None,
    }
}

pub fn signature_kind_string(value: SignatureKind) -> String {
    if let Some(name) = signature_kind_as_str(value) {
        return name.to_owned();
    }
    format!("SignatureKind({value})")
}

// --------------------------------------------------------------------------
// PORT STATUS
//   source:     internal/checker/stringer_generated.go (25 lines)
//   confidence: high
//   todos:      none tracked
//   notes:      stringer output attached to the real `types.rs` SignatureKind
//               alias/constants instead of a duplicate enum
// --------------------------------------------------------------------------
