use std::{
    fs,
    path::{Path, PathBuf},
    sync::LazyLock,
};

use regex::bytes::Regex;
use serde::Deserialize;

static LIB_INPUT_DIR: &str = "../../vendor/typescript/src/lib";
static COPYRIGHT_NOTICE: &str = "../../vendor/typescript/scripts/CopyrightNotice.txt";

pub fn main() {
    let libs = read_libs();
    generate_libs(&libs);
    generate_lib_list(&libs);
    generate_embedded(&libs);
}

struct Lib {
    target: String,       // target relative to libs dir
    sources: Vec<String>, // sources relative to src/lib dir
}

fn generate_libs(libs: &[Lib]) {
    const OUTPUT_DIR: &str = "libs";

    let copyright = read_copyright();

    fs::remove_dir_all(OUTPUT_DIR)
        .unwrap_or_else(|err| panic!("failed to remove libs directory: {err}"));

    fs::create_dir_all(OUTPUT_DIR)
        .unwrap_or_else(|err| panic!("failed to create libs directory: {err}"));

    for lib in libs {
        let mut output = Vec::new();
        output.extend_from_slice(&copyright);

        for source in &lib.sources {
            let source_path = Path::new(LIB_INPUT_DIR).join(source);
            let bytes = fs::read(&source_path)
                .unwrap_or_else(|err| panic!("failed to read {}: {err}", source_path.display()));

            output.push(b'\n');
            output.extend_from_slice(&remove_crlf(&bytes));
        }

        let output_path = Path::new(OUTPUT_DIR).join(&lib.target);
        fs::write(&output_path, output)
            .unwrap_or_else(|err| panic!("failed to write {}: {err}", output_path.display()));
    }
}

fn generate_lib_list(libs: &[Lib]) {
    let mut code = String::new();
    code.push_str("// Code generated by generate.go; DO NOT EDIT.\n\n");
    code.push_str("// LibNames is the list of all bundled lib files, sorted by name.\n");
    code.push_str("// For the list of libs sorted by load order, use [tsoptions.Libs].\n");
    code.push_str("pub static LIB_NAMES: &[&str] = &[\n");
    for lib in libs {
        code.push_str("    \"");
        code.push_str(&lib.target);
        code.push_str("\",\n");
    }
    code.push_str("];\n");

    write_code("libs_generated.rs", code.as_bytes());
}

fn generate_embedded(libs: &[Lib]) {
    let lib_var_names: Vec<_> = libs
        .iter()
        .map(|lib| format!("libs_{}", lib.target.replace('.', "_")))
        .collect();

    let mut code = String::new();
    code.push_str("//go:build !noembed\n\n");
    code.push_str("// Code generated by generate.go; DO NOT EDIT.\n\n");
    code.push_str("#![allow(non_upper_case_globals)]\n\n");

    for (i, lib) in libs.iter().enumerate() {
        let var_name = &lib_var_names[i];
        let path = Path::new("libs").join(&lib.target);
        let contents = fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
        code.push_str("static ");
        code.push_str(var_name);
        code.push_str(": &str = ");
        code.push_str(&raw_string_literal(&contents));
        code.push_str(";\n");
    }
    code.push('\n');

    code.push_str("pub static EMBEDDED_CONTENTS: &[(&str, &str)] = &[\n");
    for (i, lib) in libs.iter().enumerate() {
        let var_name = &lib_var_names[i];
        code.push_str("    (\"libs/");
        code.push_str(&lib.target);
        code.push_str("\", ");
        code.push_str(var_name);
        code.push_str("),\n");
    }
    code.push_str("];\n\n");

    code.push_str("pub static LIBS_ENTRIES: &[(&str, i64)] = &[\n");
    for (i, lib) in libs.iter().enumerate() {
        let var_name = &lib_var_names[i];
        code.push_str("    (\"");
        code.push_str(&lib.target);
        code.push_str("\", ");
        code.push_str(var_name);
        code.push_str(".len() as i64),\n");
    }
    code.push_str("];\n");

    write_code("embed_generated.rs", code.as_bytes());
}

fn raw_string_literal(text: &str) -> String {
    let mut hashes = String::new();
    while text.contains(&format!("\"{hashes}")) {
        hashes.push('#');
    }
    format!("r{hashes}\"{text}\"{hashes}")
}

// Match escaped characters, double-quoted strings, single-line comments, and multi-line comments.
static RE_JSON_COMMENTS: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r#"\\.|"(?:\\.|[^"])*"|//.*|/\*[\s\S]*?\*/"#).unwrap());
// Match double-quoted strings (to skip) or trailing commas before ] or }.
static RE_TRAILING_COMMA: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r#""(?:\\.|[^"])*"|,\s*([}\]])"#).unwrap());

// stripJSONC replaces comments and trailing commas with spaces in JSONC content,
// producing valid JSON. The input slice is mutated in place.
fn strip_jsonc(bytes: &mut [u8]) {
    for loc in RE_JSON_COMMENTS.find_iter(bytes).map(|m| m.range()) {
        if bytes[loc.start] == b'/' {
            for b in &mut bytes[loc] {
                if *b != b'\n' {
                    *b = b' ';
                }
            }
        }
    }

    for captures in RE_TRAILING_COMMA.captures_iter(bytes) {
        if captures.get(1).is_some() {
            let loc = captures.get(0).unwrap().range();
            bytes[loc.start] = b' ';
        }
    }
}

#[derive(Deserialize)]
struct LibsMeta {
    libs: Vec<String>,
    paths: std::collections::HashMap<String, String>,
}

fn read_libs() -> Vec<Lib> {
    let libs_file = Path::new(LIB_INPUT_DIR).join("libs.json");

    let mut bytes =
        fs::read(&libs_file).unwrap_or_else(|err| panic!("failed to open libs.json: {err}"));
    strip_jsonc(&mut bytes);

    let meta: LibsMeta = serde_json::from_slice(&bytes)
        .unwrap_or_else(|err| panic!("failed to parse libs.json: {err}"));

    let mut libs = Vec::new();
    for lib_name in meta.libs {
        let sources = vec![format!("{lib_name}.d.ts")];
        let target = meta
            .paths
            .get(&lib_name)
            .cloned()
            .unwrap_or_else(|| format!("lib.{lib_name}.d.ts"));
        libs.push(Lib { target, sources });
    }

    libs.sort_by(|a, b| a.target.cmp(&b.target));

    libs
}

fn read_copyright() -> Vec<u8> {
    let bytes = fs::read(COPYRIGHT_NOTICE)
        .unwrap_or_else(|err| panic!("failed to read copyright notice: {err}"));
    remove_crlf(&bytes)
}

fn remove_crlf(bytes: &[u8]) -> Vec<u8> {
    bytes.replace(b"\r\n", b"\n")
}

fn write_code(filename: &str, code: &[u8]) {
    // PORT NOTE: Go formats generated code before writing. Rust formatting is
    // left to the caller until the Rust generator is wired into the toolchain.
    fs::write(PathBuf::from(filename), code)
        .unwrap_or_else(|err| panic!("failed to write {filename}: {err}"));
}
