// Code generated by scripts/generate-go-ast.ts.
// Source: vendor/typescript-go/internal/ast/kind_stringer_generated.go

use std::fmt;

use crate::Kind;

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the AST generator to update this file.
const _: [(); Kind::Unknown as usize] = [(); 0];
const _: [(); Kind::Count as usize] = [(); Kind::Count as usize];

impl Kind {
    pub fn as_str(self) -> String {
        format!("Kind{self:?}")
    }
}

impl fmt::Display for Kind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Kind{self:?}")
    }
}
